### ISSUE TITLE
Enhancement: Can't complete habits in the future

### ISSUE THREAD

**Issue by jwfunk** [sampocs/CS506_Momentum#40]
It doesn't make sense to say that I've done something when that day hasn't even happened yet

**Comment by sampocs** [comment]
We've decided there's no reason to intentionally prevent this activity from occurring. If they user wants to complete a habit in the future (for whatever reason) they should be able to go ahead and do so. Otherwise, there is nothing forcing the user to complete a habit in the future since habits are completed manually. If they don't think it makes sense for a future activity to be completed, then they just shouldn't check it off as completed.
